import { Ifo } from './types'

const ifos: Ifo[] = [
    {
        id: 'cola',
        address: '0x06B6f6A5b49fce0B95D3516780756b541D45F20E',
        isActive: true,
        name: 'ColaFactory',
        subTitle: 'Turn Cola into cold, hard cash on PulseChain',
        description:
            'ColaFactory is a yield farming project, Which has become the standard and the most convenient way to make yield.\n' +
            'Our primary aim is to utilize the scalability, security, decentralization, and lower transaction fees offered by the PULSECHAIN Blockchain to deliver the finest product to the PULSECHAIN Ecosystem.',
        launchDate: 'Jui. 15',
        launchTime: '2PM LON',
        saleAmount: '500,000 COLA',
        raiseAmount: '$50,000',
        projectSiteUrl: 'https://colafactory.com/',
        currency: 'WPLS',
        currencyAddress: '0xA1077a294dDE1B09bB078844df40758a5D0f9a27',
        tokenDecimals: 18,
        releaseBlockNumber: 17777845,
        /* releaseBlockNumber: 17791843, */
    },
    /* {
      id: 'blink',
      address: '0x44a9Cc8463EC00937242b660BF65B10365d99baD',
      isActive: false,
      name: 'BLINk (BLK)',
      subTitle: 'Online games on BSC',
      description:
        'BLINk enables BNB holders to enjoy gaming experiences that WINk users on Tron have been enjoying for over two years.',
      launchDate: 'Nov. 20',
      launchTime: '9PM SGT',
      saleAmount: '100,000,000 BLINK',
      raiseAmount: '$1,000,000',
      cakeToBurn: '$500,000',
      projectSiteUrl: 'https://blink.wink.org',
      currency: 'cola-BUSD LP',
      currencyAddress: '0xfdf68922460d7508f84bd55acb9d276d3f9a2c31',
      tokenDecimals: 6,
      releaseBlockNumber: 3279767,
    },
    {
      id: 'ditto',
      address: '0x570c9eB19553526Fb35895a531928E19C7D20788',
      isActive: false,
      name: 'Ditto (DITTO)',
      subTitle: 'Next-gen elastic supply token',
      description:
        'Ditto is the first elastic supply token on the Binance Smart Chain. Its goal is to maintain a stable price of $1, where its supply will adapt to changes in demand. All supply changes will apply equally to every wallet holding Ditto, and holders should always have the same % of the total supply',
      launchDate: 'Dec. 23',
      launchTime: '3PM SGT',
      saleAmount: '700,000 DITTO',
      raiseAmount: '$630,000',
      cakeToBurn: '$315,000',
      projectSiteUrl: 'https://ditto.money/',
      currency: 'cola-BUSD LP',
      currencyAddress: '0xfdf68922460d7508f84bd55acb9d276d3f9a2c31',
      tokenDecimals: 9,
      releaseBlockNumber: 3279767,
    },
    {
      id: 'tenet',
      address: '0xB922aA19A2603A07C6C9ED6c236618C9bac51f06',
      isActive: false,
      name: 'Tenet (TEN)',
      subTitle: 'Cross-chain Automated Market Maker',
      description:
        'Tenet is a cross-chain Automated Market Maker (AMM) connector that provides a decentralized Liquidity Tap for various tokens. The Liquidity Tap is the powerhouse of the Liquidity Pool, employing a dynamic algorithm to give the Liquidity Provider fairer, more efficient, and richer incentives. Tenet aims to build a cross-chain and cross-platform toolkit protocol that allows the demand side to customize the parameters of the liquidity tap, allowing them to reach out to more liquidity participants effectively and with relative ease.',
      launchDate: 'Jan. 5',
      launchTime: '3PM SGT',
      saleAmount: '1,000,000 TEN',
      raiseAmount: '$1,000,000',
      cakeToBurn: '$500,000',
      projectSiteUrl: 'https://www.tenet.farm/',
      currency: 'cola-BUSD LP',
      currencyAddress: '0xfdf68922460d7508f84bd55acb9d276d3f9a2c31',
      tokenDecimals: 18,
      releaseBlockNumber: 3483883,
    },
    {
      id: 'helmet',
      address: '0xa32509d760ee47Eb2Be96D338b5d69B5FBa4eFEB',
      isActive: false,
      name: 'Helmet.insure (Helmet)',
      subTitle: 'Crypto-assets insurance trading platform',
      description:
        'Helmet is a peer-to-peer insurance protocol written with options trading logic, which allows anyone to create any insurance policy easily in the market. Helmet aims to enable DeFi users to be protected against the risk of price fluctuations by providing price-shield insurance for BSC assets. They provide suppliers with a range of insurance types to sell, giving a variety of hedging strategies to the market.',
      launchDate: 'Jan. 13',
      launchTime: '5PM SGT',
      saleAmount: '10,000,000 Helmet',
      raiseAmount: '$1,000,000',
      cakeToBurn: '$500,000',
      projectSiteUrl: 'https://www.helmet.insure/',
      currency: 'cola-BUSD LP',
      currencyAddress: '0xfdf68922460d7508f84bd55acb9d276d3f9a2c31',
      tokenDecimals: 18,
      releaseBlockNumber: 3771926,
    },

   /* {
      id: 'cakepop',
      address: '0x345c045f3573368b82da5d1b3a21250dafa889dd',
      isActive: false,
      name: 'CakePop',
      subTitle: 'A powerful new Dividend-paying token. Buy, HODL and earn CAKE passively!',
      description:
        'CakePop is a new kind of tokenomic dividend coin that aims to build deep value through marketing, transaction leverage and future platform growth. CakePop is built around the idea that branding is everything in the age of infinite choices. CakePop will launch with a standalone UI for tracking past, current and future dividends. CakePop will also introduce various farms on partner platforms like colaFinance which will create a radical number of TXs. Each TX will generate fee rewards for CAKEPOP holders and payout autonomously as CAKE Dividends!',
      launchDate: 'Aug. 30',
      launchTime: '~2PM EST',
      saleAmount: '333,333,333 CAKEPOP',
      raiseAmount: '$250,000',
      cakeToBurn: '$125,000',
      projectSiteUrl: 'https://cakepop.app',
      currency: 'cola-BUSD LP',
      currencyAddress: '0xfdf68922460d7508f84bd55acb9d276d3f9a2c31',
      tokenDecimals: 18,
      releaseBlockNumber: 10512405,
    }, */
]

export default ifos
